fix: escape Vue template syntax in prose inline code
The string `${{ github.ref == 'refs/heads/main' }}` in prose text
was being compiled by VitePress as a Vue template interpolation,
causing SSR build failures with:

  TypeError: Cannot read properties of undefined (reading 'ref')

Wrap the inline code in `<span v-pre>` to prevent Vue template
processing of the curly braces.

Signed-off-by: Eike Waldt <waldt@b1-systems.de>
On-behalf-of: SAP <eike.waldt@sap.com>